/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sandbox;

import java.io.IOException;
import java.io.StringReader;
import java.nio.file.Files;
import java.nio.file.Paths;

import javax.json.Json;
import javax.json.JsonArray;
import javax.json.JsonObject;
import javax.json.JsonReader;
import javax.json.JsonStructure;
import javax.json.JsonValue;

public class JsonConverter {

    public static void convertToCsv(String jsonPath, String outputDir) throws IOException {
        String data = Files.readString(Paths.get(jsonPath));

        JsonReader jsonReader = Json.createReader(new StringReader(data));
        JsonStructure json = jsonReader.read();

        JsonValue sender = json.getValue("/sender");
        JsonValue receiver = json.getValue("/receiver");
        JsonValue documents = json.getValue("/documents");

        JsonArray senderArray = sender.asJsonArray();
        JsonArray receiverArray = receiver.asJsonArray();
        JsonObject documentsObject = documents.asJsonObject();

        int counter = 1;

        String senderBody = "";
        for (JsonValue senderVal : senderArray) {
            JsonObject senderObj = senderVal.asJsonObject();
            senderBody += "\"" + counter + "\"," + "\"" + senderObj.getString("name") + "\"," + "\""
                    + senderObj.getString("division") + "\"" + "\n";
            counter++;
        }
        Files.writeString(Paths.get(outputDir + "sender.csv"), senderBody);

        String receiverBody = "";
        for (JsonValue receiverVal : receiverArray) {
            JsonObject receiverObj = receiverVal.asJsonObject();
            receiverBody += "\"" + counter + "\"," + "\"" + receiverObj.getString("name") + "\"," + "\""
                    + receiverObj.getString("division") + "\"" + "\n";
            counter++;
        }
        Files.writeString(Paths.get(outputDir + "receiver.csv"), receiverBody);

        String documentBody = "\"" + counter + "\"," + "\"" + documentsObject.getString("file_name") + "\"," + "\""
                + documentsObject.getString("accepted_date") + "\"";
        counter++;

        Files.writeString(Paths.get(outputDir + "documents.csv"), documentBody);
    }
}
